version: '3'
services:
  svelte-node:
    container_name: 'svelte-node'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - svelte-node:/app/node_modules
    command: npm run dev:server
  svelte-app:
    container_name: 'svelte-app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5173:5173
    command: npm run dev -- --host
volumes:
  svelte-node:
  svelte-app:
